kind: pipeline
name: default

steps:
  # - name: build
  #   image: node:8-alpine
  #   commands:
  #     - npm install
  #     - node index.js

  - name: message
    image: ubuntu
    commands:
      - apt-get update && apt-get install curl && curl -s -I https://registry.kraken.tn

  - name: docker
    image: plugins/docker
    settings:
      custom_dns: 8.8.8.8
      auto_tag: true
      repo: registry.kraken.tn/testrepo
      debug: true
      # registry: registry.kraken.tn
