kind: pipeline
name: default

steps:
  - name: build
    image: node:8-alpine
    commands:
      - npm install
      - node index.js

  - name: docker
    image: plugins/docker
    settings:
      insecure: false
      custom_dns: 8.8.8.8
      repo: registry.kraken.tn/testrepo
      registry: registry.kraken.tn
